In [16]:
import numpy as np 

a = np.ones(3)
a

array([1., 1., 1.])

In [17]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
z.shape

(10,)

In [19]:
z.shape = (10, 1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [20]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
z = np.empty(3)
z

array([1., 1., 1.])

In [22]:
z = np.linspace(2, 10, 5)
z

array([ 2.,  4.,  6.,  8., 10.])

In [23]:
z = np.array([10, 20])
z

array([10, 20])

In [24]:
a_list = [1, 2, 3, 4, 5, 6, 7]
z = np.array(a_list)
z

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
type(z)

numpy.ndarray

In [26]:
b_list = [[9, 8, 7, 6, 5], [1, 2, 3, 4, 5]]
z = np.array([b_list])
z

array([[[9, 8, 7, 6, 5],
        [1, 2, 3, 4, 5]]])

In [27]:
z.shape
?

In [28]:
np.random.seed
z1 = np.random.randint(10, size=6)
z1

array([5, 5, 8, 9, 8, 1])

In [29]:
z1[0]

5

In [30]:
z1[0:2]

array([5, 5])

In [31]:
z1[-1]

1

In [32]:
z = np.array([1, 2, 3, 4, 5])

In [33]:
z < 3

array([ True,  True, False, False, False])

In [34]:
z > 3

array([False, False, False,  True,  True])

In [35]:
z[z>3]

array([4, 5])

In [36]:
a_array = np.array([1, 2, 3, 4, 5])
b_array = np.array([6, 7, 8, 9, 10])

In [37]:
a_array + b_array

array([ 7,  9, 11, 13, 15])

In [38]:
a_array + 30

array([31, 32, 33, 34, 35])

In [39]:
a_array * b_array

array([ 6, 14, 24, 36, 50])

In [40]:
a_array * 10

array([10, 20, 30, 40, 50])

In [41]:
a_array @ b_array

130

In [42]:
a

array([1., 1., 1.])